export const SHOW_FILL_FULL_FORM_NOTIFICATION =
  'SHOW_FILL_FULL_FORM_NOTIFICATION'

export const SHOW_TOO_SHORT_INPUTS_IN_FORM = 'SHOW_TOO_SHORT_INPUTS_IN_FORM'

export const REGISTER_USER_START = 'REGISTER_USER_START'
export const REGISTER_USER_DONE = 'REGISTER_USER_DONE'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_DONE = 'LOGIN_USER_DONE'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_QUESTIONS_START = 'GET_QUESTIONS_START'
export const GET_QUESTIONS_DONE = 'GET_QUESTIONS_DONE'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const ADD_QUESTION_START = 'ADD_QUESTION_START'
export const ADD_QUESTION_DONE = 'ADD_QUESTION_DONE'
export const CLEAR_QUESTION_FORM = 'CLEAR_QUESTION_FORM'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const TRIGGER_POPUP = 'TRIGGER_POPUP'
export const CLEAR_POPUP = 'CLEAR_POPUP'
